version: '3.8'

services:
  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.16
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
      - kafka
    networks:
      - app-network
    environment:
      ZK_HOSTS: "zookeerper:2181"
      APPLICATION_SECRETL: "tc4a_secret"
    command: 
      - Dpidfile.path=/dev/null