SELECT 
    id AS event_id,
    duration AS event_duration,
    title AS event_title,
    description AS  event_description,
    language AS event_langiage,
    streaming_link,
    total_seats,
    remaining_seats,
    cpd AS cpd_points,
    start_date AS event_start_date,
    end_date AS event_end_date,
    access_mode,
    attendance_mode,
    event_type,
    amount,
    is_verified,	
    is_cert_available,
    is_active,
    created_at,
    updated_at,
    organization_id_id AS organization_id,
    banner,
    is_featured,	
    is_online,	
    recurring,
    agenda,
    group_attendance,	
    status AS event_status,
    streaming_platform, 
    venue,
    certificates_generated,
    event_link,
    registration_form_id,
    self_paced_id,
    zoom_meeting_id,
    zoom_meeting_pass,
    department_id
FROM {{source("mlh_uat", "events")}}
	