version: "3.8"

name: corisync-streaming-data-platform

services:
  network-init:
    image: busybox
    container_name: network-init
    volumes:
      - ./entry_point.sh:/entry_point.sh
    entrypoint: ["/entry_point.sh"]
    networks:
      - app-network
    restart: "no" 

  postgresql-init:
    image: postgres:alpine
    container_name: postgresql-init
    volumnes:
      - ./configs/.env:/configs/.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT:  ${POSTGRES_PORT}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./main_entry_point.sh:/main_entry_point.sh
    entrypoint: ["/main_entry_point.sh"]
    networks:
      - app-network
    restart: "no" 


include:
  - ./zookeeper/docker-compose.yaml
  - ./kafka/docker-compose.yaml
  - ./control-center/docker-compose.yaml
  - ./debezium/docker-compose.yaml
  - ./schema-registry/docker-compose.yaml
  # - ./kafka-manager/docker-compose.yaml
  - ./apache-spark/docker-compose.yaml


networks:
  app-network:
    name: app-network
    driver: bridge
