corisync_dbt:
  outputs:
    dev:
      dataset: mlh_etl
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/service_json/visualization-app-404406-7c3ab6ce47df.json
      location: US
      method: service-account
      priority: interactive
      project: visualization-app-404406
      threads: 1
      type: bigquery
  target: dev