version: "2"
services:
  debezium:
    image: debezium/connect:latest
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=dbz_config
      - OFFSET_STORAGE_TOPIC=dbz_offset
      - BOOTSTRAP_SERVERS=kafka:9092   # Kafka bootstrap server address
    volumes:
      - ./debezium-postgresql-connector.json:/etc/debezium/postgresql-connector.json
    depends_on:
      - kafka
      - zookeeper
    networks:
      - data_platform_network