version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCAL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    volumes:
      - ./kafka/config/server.properties:/etc/kafka/config/
    depends_on:
      - zookeeper
    networks:
      - app-network

  kafka_manager:
    image: hlebalbau/kafka_manager:stable
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: "zookeerper:2181"
      APPLICATION_SECRETL: "tc4a_secret"
    command: 
      - Dpidfile.path=/dev/null
