version: 2

sources:
  - name: mlh_data_warehouse
    database: visualization-app-404406
    schema: "{{ var('etl_schema') }}"
    
    tables:
    - name: organizations
      identifier: organization_organization

    - name: events
      identifier: events_event

    - name: event_enrolment
      identifier: event_enrolment_eventenrollment

    - name: attendees_details
      identifier: event_enrolment_eventuser

    - name: cadre
      identifier: events_event_specialization