SELECT 
    id AS attendee_id,
    first_name,
    last_name,
    created_at,
    updated_at,
    email,
    remember_me,
    other_info__gender AS gender,
    organization_id_id AS organization_id,
    COALESCE(
            CAST(other_info__mobile_nox AS string),
            CAST(other_info__the_critical_role_of_in_vitro_d_phone_number AS string)
            ) AS phone_number,
    COALESCE(
            CAST(other_info__registration_number_compulsory_for_cpd_issuancex AS string),
            CAST(other_info__board_registration_number_compulsory_for_cpd_issuance_if_not_available_indicate_by_n_a AS string),
            CAST(other_info__medical_board_number_kmpdc_nck_coc_ppbx AS string), 
            CAST(other_info__registration_license_number AS string), 
            CAST(other_info__board_registration_number_compulsory_for_cpd_issuancex AS string), 
            CAST(other_info__registration_practice_number AS string)
            ) AS registration_number,
    COALESCE(
             CAST(other_info__county AS string),
             CAST(other_info__the_critical_role_of_in_vitro_d_state_county_district AS string)
            ) AS county,
    COALESCE(CAST(other_info__country AS string), 
             CAST(other_info__country_region_name AS string) 
    ) AS country,
    COALESCE(other_info__profession,    
                other_info__the_critical_role_of_in_vitro_d_profession)
             AS profession,
    COALESCE(other_info__job_title, other_info___industry_job_title) AS job_title,
    COALESCE(other_info__workplace, 
            other_info__the_critical_role_of_in_vitro_d_organization_affiliation_workplacex) AS workplace
    -- other_info__specialization,
    -- other_info__can_your_email_be_used_for_future_communicationsx,
    -- other_info__ward,
    -- other_info__title,
    -- other_info__gender,
    -- other_info__location,
    -- other_info__department,
    -- other_info__board_number,
    -- other_info__workplace,
    -- other_info__terms,
    -- other_info__state,
    -- other_info__facility_type,
    -- other_info__facility_level,
    -- other_info__approval_status,
    -- other_info__staff_number,
    -- other_info__job_title,
    -- other_info__user_name_original_namex,
    -- other_info__medical_board_number_kmpdc_nck_coc_ppbx,
    -- other_info__is_guest,other_info__branch,
    -- other_info__association_name,
    -- other_info__join_time,
    -- other_info__leave_time,
    -- other_info__association,
    -- other_info__na_n,
    -- other_info__organisation_affiliation,
    -- other_info__the_critical_role_of_in_vitro_d_organization_affiliation_workplacex,
    -- other_info__x,
    -- other_info__name_of_equity_afia_working_at_affiliated_with,
    -- other_info__duration_in_session_minutesx,
    -- other_info__utm_source,
    -- other_info__utm_campaign,
    -- other_info__organization_affiliation,
    -- other_info__duration_in_session_minutesx__v_text,
    -- other_info__approv,
    -- other_info__name_of_the_workplace,
    -- other_info__organization,
    -- other_info__will_you_require_a_cpd_token_for_this_meetingx,
    -- other_info__institution,other_info__attendee_details,
    -- other_info__facility_name,
    -- other_info__type_of_staff,
    -- other_info___industry_job_title,
    -- other_info__phone,other_info__specialty,
    -- other_info__enrollment_number,
    -- other_info__privacy_statement_we_ensure_any_data_you_provide_is_held_securely_by_supplying_your_contact_information_you_authorize_the_host_and_the_sponsor_of_this_webinar_to_contact_you_with_more_content_and_information_about_products_and_servicesx,
    -- other_info__size,
    -- other_info__event_id,
    -- other_info__medical_board_kmpdc_nck_coc_ppbx,
    -- other_info__clinicbusiness_unitdepartment,
    -- other_info__industry_job_title,
    -- other_info__designation,
    -- other_info__email_consent,
    -- other_info__enrollment_number__v_text,
    -- other_info__are_you_a_person_living_with_a_non_communicable_disease_ncdx,
    -- other_info__source_name,
    -- other_info,
    -- other_info__choice_test,
    -- other_info__sector,
    -- other_info__speciality,
    -- other_info__name_of_work_place,
    -- other_info__medical_board_kmpdc_nck_coc_ppbx__v_text,
    -- other_info__phone__v_text
FROM {{source("mlh_data_warehouse","attendees_details")}}
