name: Deploy to Droplet

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the `main` branch
    paths:
      - 'services/streaming/**'  # Trigger `deploy-streaming` only if changes are made in the streaming folder
      - 'services/batch/airflow/**'  # Trigger `deploy-airflow` only if changes are made in the airflow folder
      - 'services/security/vaultwarden/**'  # Trigger `deploy-security` only if changes are made in the security folder

jobs:
  deploy-streaming:
    name: Deploy Streaming Services
    runs-on: ubuntu-20.04
    if: github.event.head_commit.modified | contains('services/streaming')  # Only run if there are changes in the streaming folder
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.VPS_IP}} >> ~/.ssh/known_hosts

      - name: Ensure repository folder and handle git setup
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          mkdir -p ~/mlh-corisync
          cd ~/mlh-corisync
          if [ ! -d .git ]; then
            git clone git@github.com:your-org-or-user/mlh-corisync.git .
          else
            git reset --hard
            git pull origin main
          fi
          EOF

      - name: Initiate Streaming
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          cd ~/mlh-corisync/services/streaming
          docker-compose down
          docker-compose up -d --build
          EOF

      - name: Initiate Connectors
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          cd ~/mlh-corisync/services/streaming/debezium
          python3 create_connectors.py
          EOF

  deploy-airflow:
    name: Deploy Airflow Services
    runs-on: ubuntu-20.04
    needs: deploy-streaming  # Ensures this job runs after deploy-streaming
    if: ${{ always() && github.event.head_commit.modified | contains('services/batch/airflow') }}  # Only run if changes are in the airflow folder
    steps:
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.VPS_IP}} >> ~/.ssh/known_hosts

      - name: Initiate Airflow
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          cd ~/mlh-corisync/services/batch/airflow
          docker-compose down
          docker-compose up -d --build
          EOF

  deploy-security:
    name: Deploy Security Services
    runs-on: ubuntu-20.04
    needs: deploy-airflow  # Ensures this job runs after deploy-airflow
    if: ${{ always() && github.event.head_commit.modified | contains('services/security/vaultwarden') }}  # Only run if changes are in the security folder
    steps:
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.VPS_IP}} >> ~/.ssh/known_hosts

      - name: Initiate Security
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          cd ~/mlh-corisync/services/security/vaultwarden
          docker-compose down
          docker-compose up -d --build
          EOF
