name: Deploy to Droplet

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the `main` branch

jobs:
  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.VPS_IP}} >> ~/.ssh/known_hosts
      - name: Ensure repository folder exists
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} "mkdir -p mlh-corisync"
      - name: Deploy application
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} <<EOF
          cd mlh-corisync
          git pull origin main
          docker-compose up -d --build
          EOF
