version: "2.4"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - cori-sync-net

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9093
      KAFKA_LISTENER_EXTERNAL: EXTERNAL://localhost:9092
      KAFKA_LISTENER_INTER_BROKER: INSIDE://kafka:9093
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - cori-sync-net

networks:
  cori-sync-net:
    driver: bridge